version: '2'
services:
  web:
    build: .
    image: gcr.io/percy_dev/web:local
    ports:
      - "8080:8080"
    shm_size: 1G
    environment:
      - DOCKER=true
      - BUILDKITE
      - BUILDKITE_COMMIT
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_ID
      - BUILDKITE_PARALLEL_JOB
      - BUILDKITE_PULL_REQUEST
      - PERCY_TOKEN
