steps:
  - label: ":percy::hamster: test"
    commands:
      - "make build-test"
      - "make test"
    timeout_in_minutes: 20
    artifact_paths:
      - "test.log"

  - label: ":percy::hamster: publish"
    branches: "master"
    commands:
      - "make publish"
    timeout_in_minutes: 20
    retry:
      automatic:
        exit_status: "*"
        limit: 2

  - wait

  - label: "deploy :rocket::percy::rocket:"
    trigger: "deploy-web"
    branches: "master"
    async: true
    build:
      message: "${BUILDKITE_MESSAGE}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        TAG: "${BUILDKITE_COMMIT}"
