retry: &retry
  manual: false
  automatic:
    - exit_status: -1  # Agent was lost
      limit: 2
    - exit_status: 2 # Observed when docker has a broken connection
      limit: 2
    - exit_status: 125 # Error response from Docker daemon
      limit: 2
    - exit_status: 255 # Forced agent shutdown often due to preemptible VMs
      limit: 2

steps:
  - label: ":percy::hamster: test runner #%n"
    command:
      - "yarn install --pure-lockfile"
      - "yarn run build-test"
      - "yarn test:parallel"
    env:
      - DOCKER=true
      - BUILDKITE
      - BUILDKITE_COMMIT
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_ID
      - BUILDKITE_PARALLEL_JOB
      - BUILDKITE_PULL_REQUEST
      - PERCY_TOKEN
    plugins:
      - docker#v3.3.0:
          image: "circleci/node:8-browsers"
          workdir: "/home/circleci/percy-web"
          propagate-environment: true
          user: "root"
    parallelism: 4
    timeout_in_minutes: 20
    retry: *retry
    artifact_paths:
      - "test.log"

  - wait: ~
    continue_on_failure: true

  - label: ":percy::checkered_flag: finalize"
    commands:
      - "percy finalize --all"
    plugins:
      - docker#v3.3.0:
          image: "percyio/agent"
          environment:
            - "PERCY_TOKEN"
            - "BUILDKITE"
            - "BUILDKITE_BUILD_ID"
            - "BUILDKITE_PARALLEL_JOB_COUNT"
    retry: *retry

  - label: ":percy::hamster: publish"
    branches: "master"
    commands:
      - "make publish"
    timeout_in_minutes: 20
    retry:
      automatic:
        exit_status: "*"
        limit: 2

  - wait

  - label: "deploy :rocket::percy::rocket:"
    trigger: "deploy-web"
    branches: "master"
    async: true
    build:
      message: "${BUILDKITE_MESSAGE}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        TAG: "${BUILDKITE_COMMIT}"
